package com.william.model;
// Generated 2018-10-17 18:23:24 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Announcement generated by hbm2java
 */
public class Announcement implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private String addUser;
	private Date createTime;
	private Byte status;

	public Announcement() {
	}

	public Announcement(String content, String addUser, Date createTime, Byte status) {
		this.content = content;
		this.addUser = addUser;
		this.createTime = createTime;
		this.status = status;
	}

	public Announcement(String title, String content, String addUser, Date createTime, Byte status) {
		this.title = title;
		this.content = content;
		this.addUser = addUser;
		this.createTime = createTime;
		this.status = status;
	}

	public Announcement(boolean b) {
		if(b){
			this.createTime = new Date(System.currentTimeMillis());
			this.status = 1;
		}
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
