package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Bussiness generated by hbm2java
 */
public class Bussiness implements java.io.Serializable {

	private Integer id;
	private String bussinessName;
	private String bussinessCode;
	private String receiptCode;
	private int ownerId;
	private byte status;
	private Date createTime;
	private Date modifyTime;

	public Bussiness() {
	}

	public Bussiness(String bussinessName, String bussinessCode, int ownerId, byte status) {
		this.bussinessName = bussinessName;
		this.bussinessCode = bussinessCode;
		this.ownerId = ownerId;
		this.status = status;
	}

	public Bussiness(String bussinessName, String bussinessCode, String receiptCode, int ownerId, byte status,
			Date createTime, Date modifyTime) {
		this.bussinessName = bussinessName;
		this.bussinessCode = bussinessCode;
		this.receiptCode = receiptCode;
		this.ownerId = ownerId;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBussinessName() {
		return this.bussinessName;
	}

	public void setBussinessName(String bussinessName) {
		this.bussinessName = bussinessName;
	}

	public String getBussinessCode() {
		return this.bussinessCode;
	}

	public void setBussinessCode(String bussinessCode) {
		this.bussinessCode = bussinessCode;
	}

	public String getReceiptCode() {
		return this.receiptCode;
	}

	public void setReceiptCode(String receiptCode) {
		this.receiptCode = receiptCode;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
