package com.william.model;
// Generated 2018-10-9 19:20:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Merchant generated by hbm2java
 */
public class Merchant implements java.io.Serializable {

	private Integer id;
	private String merchantName;
	private String no;
	private Integer storeId;
	private Date createTime;
	private Date updateTime;
	private byte status;
	private Byte delTf;

	public Merchant() {
	}

	public Merchant(String merchantName, byte status) {
		this.merchantName = merchantName;
		this.status = status;
	}

	public Merchant(String merchantName, String no, Integer storeId, Date createTime, Date updateTime, byte status,
			Byte delTf) {
		this.merchantName = merchantName;
		this.no = no;
		this.storeId = storeId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
		this.delTf = delTf;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Byte getDelTf() {
		return this.delTf;
	}

	public void setDelTf(Byte delTf) {
		this.delTf = delTf;
	}

}
