package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SysMenu generated by hbm2java
 */
public class SysMenu implements java.io.Serializable {

	private Integer menuId;
	private Integer parentId;
	private String menuName;
	private String menuIcon;
	private String menuUrl;
	private String menuType;
	private String menuOrder;
	private String menuStatus;
	private Set sysRolePermissions = new HashSet(0);

	public SysMenu() {
	}

	public SysMenu(Integer parentId, String menuName, String menuIcon, String menuUrl, String menuType,
			String menuOrder, String menuStatus, Set sysRolePermissions) {
		this.parentId = parentId;
		this.menuName = menuName;
		this.menuIcon = menuIcon;
		this.menuUrl = menuUrl;
		this.menuType = menuType;
		this.menuOrder = menuOrder;
		this.menuStatus = menuStatus;
		this.sysRolePermissions = sysRolePermissions;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public String getMenuOrder() {
		return this.menuOrder;
	}

	public void setMenuOrder(String menuOrder) {
		this.menuOrder = menuOrder;
	}

	public String getMenuStatus() {
		return this.menuStatus;
	}

	public void setMenuStatus(String menuStatus) {
		this.menuStatus = menuStatus;
	}

	public Set getSysRolePermissions() {
		return this.sysRolePermissions;
	}

	public void setSysRolePermissions(Set sysRolePermissions) {
		this.sysRolePermissions = sysRolePermissions;
	}

}
