package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

/**
 * SysRolePermission generated by hbm2java
 */
public class SysRolePermission implements java.io.Serializable {

	private Integer rpid;
	private SysMenu sysMenu;
	private SysRole sysRole;

	public SysRolePermission() {
	}

	public SysRolePermission(SysMenu sysMenu, SysRole sysRole) {
		this.sysMenu = sysMenu;
		this.sysRole = sysRole;
	}

	public Integer getRpid() {
		return this.rpid;
	}

	public void setRpid(Integer rpid) {
		this.rpid = rpid;
	}

	public SysMenu getSysMenu() {
		return this.sysMenu;
	}

	public void setSysMenu(SysMenu sysMenu) {
		this.sysMenu = sysMenu;
	}

	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

}
