package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String tokenId;
	private Byte clientType;
	private Date createTime;
	private Date expireTime;

	public Token() {
	}

	public Token(int userId, String tokenId) {
		this.userId = userId;
		this.tokenId = tokenId;
	}

	public Token(int userId, String tokenId, Byte clientType, Date createTime, Date expireTime) {
		this.userId = userId;
		this.tokenId = tokenId;
		this.clientType = clientType;
		this.createTime = createTime;
		this.expireTime = expireTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	public Byte getClientType() {
		return this.clientType;
	}

	public void setClientType(Byte clientType) {
		this.clientType = clientType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

}
