package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final



/**
 * UserPayControl generated by hbm2java
 */
public class UserPayControl  implements java.io.Serializable {


     private int userId;
     private byte qqPayStatus;
     private byte h5qqPayStatus;
     private byte wxPayStatus;
     private byte h5wxPayStatus;
     private byte aliPayStatus;
     private byte h5aliPayStatus;
     private byte jdPayStatus;
     private byte unionPayPayStatus;
     private byte bankPayPayStatus;
     private byte h5bankPayStatus;
     private byte quickPayStatus;
     private byte toPayStatus;
     private byte forwardStatus;
     private byte apiPayStatus;
     private byte apitoPayStatus;
     private byte apiForwordStatus;

    public UserPayControl() {
    }

    public UserPayControl(int userId, byte qqPayStatus, byte h5qqPayStatus, byte wxPayStatus, byte h5wxPayStatus, byte aliPayStatus, byte h5aliPayStatus, byte jdPayStatus, byte unionPayPayStatus, byte bankPayPayStatus, byte h5bankPayStatus, byte quickPayStatus, byte toPayStatus, byte forwardStatus, byte apiPayStatus, byte apitoPayStatus, byte apiForwordStatus) {
       this.userId = userId;
       this.qqPayStatus = qqPayStatus;
       this.h5qqPayStatus = h5qqPayStatus;
       this.wxPayStatus = wxPayStatus;
       this.h5wxPayStatus = h5wxPayStatus;
       this.aliPayStatus = aliPayStatus;
       this.h5aliPayStatus = h5aliPayStatus;
       this.jdPayStatus = jdPayStatus;
       this.unionPayPayStatus = unionPayPayStatus;
       this.bankPayPayStatus = bankPayPayStatus;
       this.h5bankPayStatus = h5bankPayStatus;
       this.quickPayStatus = quickPayStatus;
       this.toPayStatus = toPayStatus;
       this.forwardStatus = forwardStatus;
       this.apiPayStatus = apiPayStatus;
       this.apitoPayStatus = apitoPayStatus;
       this.apiForwordStatus = apiForwordStatus;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public byte getQqPayStatus() {
        return this.qqPayStatus;
    }
    
    public void setQqPayStatus(byte qqPayStatus) {
        this.qqPayStatus = qqPayStatus;
    }
    public byte getH5qqPayStatus() {
        return this.h5qqPayStatus;
    }
    
    public void setH5qqPayStatus(byte h5qqPayStatus) {
        this.h5qqPayStatus = h5qqPayStatus;
    }
    public byte getWxPayStatus() {
        return this.wxPayStatus;
    }
    
    public void setWxPayStatus(byte wxPayStatus) {
        this.wxPayStatus = wxPayStatus;
    }
    public byte getH5wxPayStatus() {
        return this.h5wxPayStatus;
    }
    
    public void setH5wxPayStatus(byte h5wxPayStatus) {
        this.h5wxPayStatus = h5wxPayStatus;
    }
    public byte getAliPayStatus() {
        return this.aliPayStatus;
    }
    
    public void setAliPayStatus(byte aliPayStatus) {
        this.aliPayStatus = aliPayStatus;
    }
    public byte getH5aliPayStatus() {
        return this.h5aliPayStatus;
    }
    
    public void setH5aliPayStatus(byte h5aliPayStatus) {
        this.h5aliPayStatus = h5aliPayStatus;
    }
    public byte getJdPayStatus() {
        return this.jdPayStatus;
    }
    
    public void setJdPayStatus(byte jdPayStatus) {
        this.jdPayStatus = jdPayStatus;
    }
    public byte getUnionPayPayStatus() {
        return this.unionPayPayStatus;
    }
    
    public void setUnionPayPayStatus(byte unionPayPayStatus) {
        this.unionPayPayStatus = unionPayPayStatus;
    }
    public byte getBankPayPayStatus() {
        return this.bankPayPayStatus;
    }
    
    public void setBankPayPayStatus(byte bankPayPayStatus) {
        this.bankPayPayStatus = bankPayPayStatus;
    }
    public byte getH5bankPayStatus() {
        return this.h5bankPayStatus;
    }
    
    public void setH5bankPayStatus(byte h5bankPayStatus) {
        this.h5bankPayStatus = h5bankPayStatus;
    }
    public byte getQuickPayStatus() {
        return this.quickPayStatus;
    }
    
    public void setQuickPayStatus(byte quickPayStatus) {
        this.quickPayStatus = quickPayStatus;
    }
    public byte getToPayStatus() {
        return this.toPayStatus;
    }
    
    public void setToPayStatus(byte toPayStatus) {
        this.toPayStatus = toPayStatus;
    }
    public byte getForwardStatus() {
        return this.forwardStatus;
    }
    
    public void setForwardStatus(byte forwardStatus) {
        this.forwardStatus = forwardStatus;
    }
    public byte getApiPayStatus() {
        return this.apiPayStatus;
    }
    
    public void setApiPayStatus(byte apiPayStatus) {
        this.apiPayStatus = apiPayStatus;
    }
    public byte getApitoPayStatus() {
        return this.apitoPayStatus;
    }
    
    public void setApitoPayStatus(byte apitoPayStatus) {
        this.apitoPayStatus = apitoPayStatus;
    }
    public byte getApiForwordStatus() {
        return this.apiForwordStatus;
    }
    
    public void setApiForwordStatus(byte apiForwordStatus) {
        this.apiForwordStatus = apiForwordStatus;
    }




}


