package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String loginPassword;
	private String saltLogin;
	private String payPassword;
	private String saltPay;
	private String phone;
	private Byte type;
	private byte status;
	private Integer recommendId;
	private String avatar;
	private Date birthday;
	private byte sex;
	private Integer age;
	private String nickName;
	private Byte frozen;
	private Date createTime;
	private Date modifyTime;
	private byte delTf;
	private Integer merchantId;
	private String openId;
	private String email;
	private String realName;

	public User() {
	}

	public User(byte status, byte sex, byte delTf) {
		this.status = status;
		this.sex = sex;
		this.delTf = delTf;
	}

	public User(String username, String loginPassword, String saltLogin, String payPassword, String saltPay,
			String phone, Byte type, byte status, Integer recommendId, String avatar, Date birthday, byte sex,
			Integer age, String nickName, Byte frozen, Date createTime, Date modifyTime, byte delTf, Integer merchantId,
			String openId, String email, String realName) {
		this.username = username;
		this.loginPassword = loginPassword;
		this.saltLogin = saltLogin;
		this.payPassword = payPassword;
		this.saltPay = saltPay;
		this.phone = phone;
		this.type = type;
		this.status = status;
		this.recommendId = recommendId;
		this.avatar = avatar;
		this.birthday = birthday;
		this.sex = sex;
		this.age = age;
		this.nickName = nickName;
		this.frozen = frozen;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.delTf = delTf;
		this.merchantId = merchantId;
		this.openId = openId;
		this.email = email;
		this.realName = realName;
	}

	public User(boolean b) {
		if(b){
			this.status = 1;
			this.frozen = 0;
			this.createTime = new Date(System.currentTimeMillis());
			this.modifyTime = new Date(System.currentTimeMillis());
			this.delTf = 0;
		}
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public String getSaltLogin() {
		return this.saltLogin;
	}

	public void setSaltLogin(String saltLogin) {
		this.saltLogin = saltLogin;
	}

	public String getPayPassword() {
		return this.payPassword;
	}

	public void setPayPassword(String payPassword) {
		this.payPassword = payPassword;
	}

	public String getSaltPay() {
		return this.saltPay;
	}

	public void setSaltPay(String saltPay) {
		this.saltPay = saltPay;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Integer getRecommendId() {
		return this.recommendId;
	}

	public void setRecommendId(Integer recommendId) {
		this.recommendId = recommendId;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public byte getSex() {
		return this.sex;
	}

	public void setSex(byte sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Byte getFrozen() {
		return this.frozen;
	}

	public void setFrozen(Byte frozen) {
		this.frozen = frozen;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public byte getDelTf() {
		return this.delTf;
	}

	public void setDelTf(byte delTf) {
		this.delTf = delTf;
	}

	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

}
