package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final


import java.util.Date;

/**
 * UserBank generated by hbm2java
 */
public class UserBank  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private String bankCode;
     private String cardBin;
     private byte status;
     private Date createTime;
     private Date modifyTime;

    public UserBank() {
    }

	
    public UserBank(int userId, String bankCode, byte status, Date createTime, Date modifyTime) {
        this.userId = userId;
        this.bankCode = bankCode;
        this.status = status;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }
    public UserBank(int userId, String bankCode, String cardBin, byte status, Date createTime, Date modifyTime) {
       this.userId = userId;
       this.bankCode = bankCode;
       this.cardBin = cardBin;
       this.status = status;
       this.createTime = createTime;
       this.modifyTime = modifyTime;
    }
   
    public UserBank(Integer userId, String bankCode, String cardBin) {
    	this.userId = userId;
        this.bankCode = bankCode;
        this.cardBin = cardBin;
	}


	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }
    public String getCardBin() {
        return this.cardBin;
    }
    
    public void setCardBin(String cardBin) {
        this.cardBin = cardBin;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getModifyTime() {
        return this.modifyTime;
    }
    
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }




}


