package com.william.model;
// Generated 2018-10-17 18:32:00 by Hibernate Tools 4.3.5.Final

/**
 * UserRate generated by hbm2java
 */
public class UserRate implements java.io.Serializable {

	private int userId;
	private String qqPay;
	private String h5qqPay;
	private String wxPay;
	private String h5wxPay;
	private String aliPay;
	private String h5aliPay;
	private String jdPay;
	private String unionPay;
	private String bankPay;
	private String h5bankPay;
	private String quickPay;
	private String toPay;
	private String forward;
	private String quota;
	private String totalQuota;

	public UserRate() {
	}

	public UserRate(int userId, String qqPay, String h5qqPay, String wxPay, String h5wxPay, String aliPay,
			String h5aliPay, String jdPay, String unionPay, String bankPay, String h5bankPay, String quickPay,
			String toPay, String forward, String quota, String totalQuota) {
		this.userId = userId;
		this.qqPay = qqPay;
		this.h5qqPay = h5qqPay;
		this.wxPay = wxPay;
		this.h5wxPay = h5wxPay;
		this.aliPay = aliPay;
		this.h5aliPay = h5aliPay;
		this.jdPay = jdPay;
		this.unionPay = unionPay;
		this.bankPay = bankPay;
		this.h5bankPay = h5bankPay;
		this.quickPay = quickPay;
		this.toPay = toPay;
		this.forward = forward;
		this.quota = quota;
		this.totalQuota = totalQuota;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getQqPay() {
		return this.qqPay;
	}

	public void setQqPay(String qqPay) {
		this.qqPay = qqPay;
	}

	public String getH5qqPay() {
		return this.h5qqPay;
	}

	public void setH5qqPay(String h5qqPay) {
		this.h5qqPay = h5qqPay;
	}

	public String getWxPay() {
		return this.wxPay;
	}

	public void setWxPay(String wxPay) {
		this.wxPay = wxPay;
	}

	public String getH5wxPay() {
		return this.h5wxPay;
	}

	public void setH5wxPay(String h5wxPay) {
		this.h5wxPay = h5wxPay;
	}

	public String getAliPay() {
		return this.aliPay;
	}

	public void setAliPay(String aliPay) {
		this.aliPay = aliPay;
	}

	public String getH5aliPay() {
		return this.h5aliPay;
	}

	public void setH5aliPay(String h5aliPay) {
		this.h5aliPay = h5aliPay;
	}

	public String getJdPay() {
		return this.jdPay;
	}

	public void setJdPay(String jdPay) {
		this.jdPay = jdPay;
	}

	public String getUnionPay() {
		return this.unionPay;
	}

	public void setUnionPay(String unionPay) {
		this.unionPay = unionPay;
	}

	public String getBankPay() {
		return this.bankPay;
	}

	public void setBankPay(String bankPay) {
		this.bankPay = bankPay;
	}

	public String getH5bankPay() {
		return this.h5bankPay;
	}

	public void setH5bankPay(String h5bankPay) {
		this.h5bankPay = h5bankPay;
	}

	public String getQuickPay() {
		return this.quickPay;
	}

	public void setQuickPay(String quickPay) {
		this.quickPay = quickPay;
	}

	public String getToPay() {
		return this.toPay;
	}

	public void setToPay(String toPay) {
		this.toPay = toPay;
	}

	public String getForward() {
		return this.forward;
	}

	public void setForward(String forward) {
		this.forward = forward;
	}

	public String getQuota() {
		return this.quota;
	}

	public void setQuota(String quota) {
		this.quota = quota;
	}

	public String getTotalQuota() {
		return this.totalQuota;
	}

	public void setTotalQuota(String totalQuota) {
		this.totalQuota = totalQuota;
	}

}
